module.exports = {
  discord: {
    prefix: '-',
    mainChannel: '107541159357739008',
    monkeyChannel: '768157293048758325',
    replyTimeout: 5000,
  },
  islamicGreetings: [
    'selamın aleyküm',
    'sa',
    's.a',
    's.a.',
  ],
  rizaNicknames: [
    'rıza',
    'riza',
    'r1z4',
    'rjz4',
  ],
  filters: [
    '8D',
    'bassboost',
    'flanger',
    'gate',
    'haas',
    'karaoke',
    'mcompand',
    'nightcore',
    'normalizer',
    'phaser',
    'pulsator',
    'reverse',
    'subboost',
    'surrounding',
    'treble',
    'tremolo',
    'vaporwave',
    'vibrato',
  ],
};
